version: '3.4'

services:
  controledegastos:
    image: ${DOCKER_REGISTRY-}controledegastos
    build:
      context: .
      dockerfile: ControleDeGastos/Dockerfile   
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=0.0.0.0;Port=5432;Database=api.db;Username=postgres;Password=1234

    networks:
      - controle_gastos
      
     
  postgres:
    image: postgres:alpine3.15
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=api.db
    ports:
      - 5432:5432  
    networks:
      - controle_gastos

networks:
  controle_gastos:
    driver: bridge







